services:
  - type: web
    name: edugenie
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: OPENROUTER_MODEL
        value: openrouter/free
      - key: OPENROUTER_API_KEY
        sync: false

